#!/bin/sh

# util
alias path='echo -e ${PATH//:/\\n} | sort'

# ls (GNU and MacOS support)
if ls --color > /dev/null 2>&1; then
    colorflag='--color=auto'
else
    colorflag='-G'
fi
alias ls="command ls $colorflag"
unset colorflag

alias ll='ls -lF'
alias la='ls -laF'
alias la-='ls -laF | grep --color=never ^-'
alias lad='ls -laF | grep --color=never ^d'
alias lal='ls -laF | grep --color=never ^l'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
