#!/bin/sh

export LANG=en_US.UTF-8

ARCHFLAGS="$(uname -m)"
export ARCHFLAGS

# nvim > all
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"

# gcc
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
