#!/bin/sh

export LANG=en_US.UTF-8

export ARCHFLAGS="-arch $(uname -m)"

# nvim > all
export EDITOR="nvim"
export VISUAL="nvim"

# gcc
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
