#!/bin/sh

# ls (GNU and MacOS support)
if ls --color 1>/dev/null 2>&1; then
    alias ls='command ls --color=auto'
else
    alias ls='command ls -G'
fi

# grep
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias fgrep='grep -F --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'

# idk
alias ip='ip -c'
alias lspath='echo $PATH | sed -e "s,:,\n,g" | sort'

# shell RCs
alias bashrc='$EDITOR $HOME/.bashrc'
alias zshrc='$EDITOR $HOME/.zshrc'
