#!/bin/sh

# LS_COLORS
if command -v vivid 1>/dev/null; then
    export LS_COLORS="$(vivid generate snazzy)"
fi

# EDITOR / VISUAL
for e in nvim vim nano; do
    if command -v $e 1>/dev/null; then
        export EDITOR="$(which $e)"
        export VISUAL="$(which $e)"
        break
    fi
done
